from typing import Literal, TypedDict

from .user import AccessLevel

ProjectsOrderBy = Literal["id", "name", "path", "created_at", "updated_at", "last_activity_at", "similarity"]


class _Access(TypedDict):
    """Модель описывающая доступ к репозиторию/группе

    Args:
        access_level: классификация уровня доступа
        notification_level: классификация уровня отсылаемых уведомлений
    """
    access_level: AccessLevel
    notification_level: int


class _Permissions(TypedDict):
    """Модель описывающая доступы к репозиторию и группе

    Args:
        project_access: модель описывающшая доступ к репозиторию
        group_access: модель описывающшая доступ к группе
    """
    project_access: _Access | None
    group_access: _Access| None


class _Project(TypedDict):
    """Базовая модель описывающая репозиторий в GitLab

    Args:
        id: идентификатор репозитория

    Example:
        {
            "id": 10,
            "description": None,
            "name": "2ae92d16-890f-4a38-b034-06c8c126eee6",
            "name_with_namespace": "Administrator / 2ae92d16-890f-4a38-b034-06c8c126eee6",
            "path": "2ae92d16-890f-4a38-b034-06c8c126eee6",
            "path_with_namespace": "root/2ae92d16-890f-4a38-b034-06c8c126eee6",
            "created_at": "2024-02-13T21:50:44.824Z",
            "default_branch": "main",
            "tag_list": [],
            "topics": [],
            "ssh_url_to_repo": "git@localhost:root/2ae92d16-890f-4a38-b034-06c8c126eee6.git",
            "http_url_to_repo": "http://localhost/root/2ae92d16-890f-4a38-b034-06c8c126eee6.git",
            "web_url": "http://localhost/root/2ae92d16-890f-4a38-b034-06c8c126eee6",
            "readme_url": "http://localhost/root/2ae92d16-890f-4a38-b034-06c8c126eee6/-/blob/main/README.md",
            "forks_count": 0,
            "avatar_url": None,
            "star_count": 0,
            "last_activity_at": "2024-02-13T21:50:44.824Z",
            "namespace": {
                "id": 1,
                "name": "Administrator",
                "path": "root",
                "kind": "user",
                "full_path": "root",
                "parent_id": None,
                "avatar_url": "https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon",
                "web_url": "http://localhost/root"
            },
            "repository_storage": "default",
            "_links": {
                "self": "http://localhost/api/v4/projects/10",
                "issues": "http://localhost/api/v4/projects/10/issues",
                "merge_requests": "http://localhost/api/v4/projects/10/merge_requests",
                "repo_branches": "http://localhost/api/v4/projects/10/repository/branches",
                "labels": "http://localhost/api/v4/projects/10/labels",
                "events": "http://localhost/api/v4/projects/10/events",
                "members": "http://localhost/api/v4/projects/10/members",
                "cluster_agents": "http://localhost/api/v4/projects/10/cluster_agents"
            },
            "packages_enabled": True,
            "empty_repo": False,
            "archived": False,
            "visibility": "private",
            "owner": {
                "id": 1,
                "username": "root",
                "name": "Administrator",
                "state": "active",
                "locked": False,
                "avatar_url": "https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon",
                "web_url": "http://localhost/root"
            },
            "resolve_outdated_diff_discussions": False,
            "container_expiration_policy": {
                "cadence": "1d",
                "enabled": False,
                "keep_n": 10,
                "older_than": "90d",
                "name_regex": ".*",
                "name_regex_keep": None,
                "next_run_at": "2024-02-14T21:50:45.030Z"
            },
            "issues_enabled": True,
            "merge_requests_enabled": True,
            "wiki_enabled": True,
            "jobs_enabled": True,
            "snippets_enabled": True,
            "container_registry_enabled": True,
            "service_desk_enabled": False,
            "service_desk_address": None,
            "can_create_merge_request_in": True,
            "issues_access_level": "enabled",
            "repository_access_level": "enabled",
            "merge_requests_access_level": "enabled",
            "forking_access_level": "enabled",
            "wiki_access_level": "enabled",
            "builds_access_level": "enabled",
            "snippets_access_level": "enabled",
            "pages_access_level": "private",
            "analytics_access_level": "enabled",
            "container_registry_access_level": "enabled",
            "security_and_compliance_access_level": "private",
            "releases_access_level": "enabled",
            "environments_access_level": "enabled",
            "feature_flags_access_level": "enabled",
            "infrastructure_access_level": "enabled",
            "monitor_access_level": "enabled",
            "model_experiments_access_level": "enabled",
            "emails_disabled": False,
            "emails_enabled": True,
            "shared_runners_enabled": True,
            "lfs_enabled": True,
            "creator_id": 1,
            "import_url": None,
            "import_type": None,
            "import_status": "none",
            "open_issues_count": 0,
            "description_html": "",
            "updated_at": "2024-02-13T21:50:44.824Z",
            "ci_default_git_depth": 20,
            "ci_forward_deployment_enabled": True,
            "ci_forward_deployment_rollback_allowed": True,
            "ci_job_token_scope_enabled": False,
            "ci_separated_caches": True,
            "ci_allow_fork_pipelines_to_run_in_parent_project": True,
            "build_git_strategy": "fetch",
            "keep_latest_artifact": True,
            "restrict_user_defined_variables": False,
            "runners_token": "GR1348941JrYo2y6zAyBXmQ5KzZfm",
            "runner_token_expiration_interval": None,
            "group_runners_enabled": True,
            "auto_cancel_pending_pipelines": "enabled",
            "build_timeout": 3600,
            "auto_devops_enabled": True,
            "auto_devops_deploy_strategy": "continuous",
            "ci_config_path": None,
            "public_jobs": True,
            "shared_with_groups": [],
            "only_allow_merge_if_pipeline_succeeds": True,
            "allow_merge_on_skipped_pipeline": None,
            "request_access_enabled": True,
            "only_allow_merge_if_all_discussions_are_resolved": True,
            "remove_source_branch_after_merge": True,
            "printing_merge_request_link_enabled": True,
            "merge_method": "merge",
            "squash_option": "default_off",
            "enforce_auth_checks_on_uploads": True,
            "suggestion_commit_message": None,
            "merge_commit_template": None,
            "squash_commit_template": None,
            "issue_branch_template": None,
            "autoclose_referenced_issues": True,
            "requirements_enabled": False,
            "requirements_access_level": "enabled",
            "security_and_compliance_enabled": True,
            "compliance_frameworks": []
        }
    """
    id: int


class CreatedProject(_Project):
    """Модель описывающая репозиторий в GitLab непосредственно после его создания

    Args:
        import_error: были ли ошибки при импорте репозитория из других git-хранилищ (None - не импортировалось)

    Example:
        {
            "id": 10,
            "description": None,
            "name": "2ae92d16-890f-4a38-b034-06c8c126eee6",
            "name_with_namespace": "Administrator / 2ae92d16-890f-4a38-b034-06c8c126eee6",
            "path": "2ae92d16-890f-4a38-b034-06c8c126eee6",
            "path_with_namespace": "root/2ae92d16-890f-4a38-b034-06c8c126eee6",
            "created_at": "2024-02-13T21:50:44.824Z",
            "default_branch": "main",
            "tag_list": [],
            "topics": [],
            "ssh_url_to_repo": "git@localhost:root/2ae92d16-890f-4a38-b034-06c8c126eee6.git",
            "http_url_to_repo": "http://localhost/root/2ae92d16-890f-4a38-b034-06c8c126eee6.git",
            "web_url": "http://localhost/root/2ae92d16-890f-4a38-b034-06c8c126eee6",
            "readme_url": "http://localhost/root/2ae92d16-890f-4a38-b034-06c8c126eee6/-/blob/main/README.md",
            "forks_count": 0,
            "avatar_url": None,
            "star_count": 0,
            "last_activity_at": "2024-02-13T21:50:44.824Z",
            "namespace": {
                "id": 1,
                "name": "Administrator",
                "path": "root",
                "kind": "user",
                "full_path": "root",
                "parent_id": None,
                "avatar_url": "https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon",
                "web_url": "http://localhost/root"
            },
            "repository_storage": "default",
            "_links": {
                "self": "http://localhost/api/v4/projects/10",
                "issues": "http://localhost/api/v4/projects/10/issues",
                "merge_requests": "http://localhost/api/v4/projects/10/merge_requests",
                "repo_branches": "http://localhost/api/v4/projects/10/repository/branches",
                "labels": "http://localhost/api/v4/projects/10/labels",
                "events": "http://localhost/api/v4/projects/10/events",
                "members": "http://localhost/api/v4/projects/10/members",
                "cluster_agents": "http://localhost/api/v4/projects/10/cluster_agents"
            },
            "packages_enabled": True,
            "empty_repo": False,
            "archived": False,
            "visibility": "private",
            "owner": {
                "id": 1,
                "username": "root",
                "name": "Administrator",
                "state": "active",
                "locked": False,
                "avatar_url": "https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon",
                "web_url": "http://localhost/root"
            },
            "resolve_outdated_diff_discussions": False,
            "container_expiration_policy": {
                "cadence": "1d",
                "enabled": False,
                "keep_n": 10,
                "older_than": "90d",
                "name_regex": ".*",
                "name_regex_keep": None,
                "next_run_at": "2024-02-14T21:50:45.030Z"
            },
            "issues_enabled": True,
            "merge_requests_enabled": True,
            "wiki_enabled": True,
            "jobs_enabled": True,
            "snippets_enabled": True,
            "container_registry_enabled": True,
            "service_desk_enabled": False,
            "service_desk_address": None,
            "can_create_merge_request_in": True,
            "issues_access_level": "enabled",
            "repository_access_level": "enabled",
            "merge_requests_access_level": "enabled",
            "forking_access_level": "enabled",
            "wiki_access_level": "enabled",
            "builds_access_level": "enabled",
            "snippets_access_level": "enabled",
            "pages_access_level": "private",
            "analytics_access_level": "enabled",
            "container_registry_access_level": "enabled",
            "security_and_compliance_access_level": "private",
            "releases_access_level": "enabled",
            "environments_access_level": "enabled",
            "feature_flags_access_level": "enabled",
            "infrastructure_access_level": "enabled",
            "monitor_access_level": "enabled",
            "model_experiments_access_level": "enabled",
            "emails_disabled": False,
            "emails_enabled": True,
            "shared_runners_enabled": True,
            "lfs_enabled": True,
            "creator_id": 1,
            "import_url": None,
            "import_type": None,
            "import_status": "none",
            "import_error": None,
            "open_issues_count": 0,
            "description_html": "",
            "updated_at": "2024-02-13T21:50:44.824Z",
            "ci_default_git_depth": 20,
            "ci_forward_deployment_enabled": True,
            "ci_forward_deployment_rollback_allowed": True,
            "ci_job_token_scope_enabled": False,
            "ci_separated_caches": True,
            "ci_allow_fork_pipelines_to_run_in_parent_project": True,
            "build_git_strategy": "fetch",
            "keep_latest_artifact": True,
            "restrict_user_defined_variables": False,
            "runners_token": "GR1348941JrYo2y6zAyBXmQ5KzZfm",
            "runner_token_expiration_interval": None,
            "group_runners_enabled": True,
            "auto_cancel_pending_pipelines": "enabled",
            "build_timeout": 3600,
            "auto_devops_enabled": True,
            "auto_devops_deploy_strategy": "continuous",
            "ci_config_path": None,
            "public_jobs": True,
            "shared_with_groups": [],
            "only_allow_merge_if_pipeline_succeeds": True,
            "allow_merge_on_skipped_pipeline": None,
            "request_access_enabled": True,
            "only_allow_merge_if_all_discussions_are_resolved": True,
            "remove_source_branch_after_merge": True,
            "printing_merge_request_link_enabled": True,
            "merge_method": "merge",
            "squash_option": "default_off",
            "enforce_auth_checks_on_uploads": True,
            "suggestion_commit_message": None,
            "merge_commit_template": None,
            "squash_commit_template": None,
            "issue_branch_template": None,
            "autoclose_referenced_issues": True,
            "requirements_enabled": False,
            "requirements_access_level": "enabled",
            "security_and_compliance_enabled": True,
            "compliance_frameworks": []
        }
    """
    import_error: bool | None


class Project(_Project):
    """Модель описывающая созданный репозиторий в GitLab

    Example:
        {
            "id": 10,
            "description": None,
            "name": "2ae92d16-890f-4a38-b034-06c8c126eee6",
            "name_with_namespace": "Administrator / 2ae92d16-890f-4a38-b034-06c8c126eee6",
            "path": "2ae92d16-890f-4a38-b034-06c8c126eee6",
            "path_with_namespace": "root/2ae92d16-890f-4a38-b034-06c8c126eee6",
            "created_at": "2024-02-13T21:50:44.824Z",
            "default_branch": "main",
            "tag_list": [],
            "topics": [],
            "ssh_url_to_repo": "git@localhost:root/2ae92d16-890f-4a38-b034-06c8c126eee6.git",
            "http_url_to_repo": "http://localhost/root/2ae92d16-890f-4a38-b034-06c8c126eee6.git",
            "web_url": "http://localhost/root/2ae92d16-890f-4a38-b034-06c8c126eee6",
            "readme_url": "http://localhost/root/2ae92d16-890f-4a38-b034-06c8c126eee6/-/blob/main/README.md",
            "forks_count": 0,
            "avatar_url": None,
            "star_count": 0,
            "last_activity_at": "2024-02-13T21:50:44.824Z",
            "namespace": {
                "id": 1,
                "name": "Administrator",
                "path": "root",
                "kind": "user",
                "full_path": "root",
                "parent_id": None,
                "avatar_url": "https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon",
                "web_url": "http://localhost/root"
            },
            "repository_storage": "default",
            "_links": {
                "self": "http://localhost/api/v4/projects/10",
                "issues": "http://localhost/api/v4/projects/10/issues",
                "merge_requests": "http://localhost/api/v4/projects/10/merge_requests",
                "repo_branches": "http://localhost/api/v4/projects/10/repository/branches",
                "labels": "http://localhost/api/v4/projects/10/labels",
                "events": "http://localhost/api/v4/projects/10/events",
                "members": "http://localhost/api/v4/projects/10/members",
                "cluster_agents": "http://localhost/api/v4/projects/10/cluster_agents"
            },
            "packages_enabled": True,
            "empty_repo": False,
            "archived": False,
            "visibility": "private",
            "owner": {
                "id": 1,
                "username": "root",
                "name": "Administrator",
                "state": "active",
                "locked": False,
                "avatar_url": "https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon",
                "web_url": "http://localhost/root"
            },
            "resolve_outdated_diff_discussions": False,
            "container_expiration_policy": {
                "cadence": "1d",
                "enabled": False,
                "keep_n": 10,
                "older_than": "90d",
                "name_regex": ".*",
                "name_regex_keep": None,
                "next_run_at": "2024-02-14T21:50:45.030Z"
            },
            "issues_enabled": True,
            "merge_requests_enabled": True,
            "wiki_enabled": True,
            "jobs_enabled": True,
            "snippets_enabled": True,
            "container_registry_enabled": True,
            "service_desk_enabled": False,
            "service_desk_address": None,
            "can_create_merge_request_in": True,
            "issues_access_level": "enabled",
            "repository_access_level": "enabled",
            "merge_requests_access_level": "enabled",
            "forking_access_level": "enabled",
            "wiki_access_level": "enabled",
            "builds_access_level": "enabled",
            "snippets_access_level": "enabled",
            "pages_access_level": "private",
            "analytics_access_level": "enabled",
            "container_registry_access_level": "enabled",
            "security_and_compliance_access_level": "private",
            "releases_access_level": "enabled",
            "environments_access_level": "enabled",
            "feature_flags_access_level": "enabled",
            "infrastructure_access_level": "enabled",
            "monitor_access_level": "enabled",
            "model_experiments_access_level": "enabled",
            "emails_disabled": False,
            "emails_enabled": True,
            "shared_runners_enabled": True,
            "lfs_enabled": True,
            "creator_id": 1,
            "import_url": None,
            "import_type": None,
            "import_status": "none",
            "open_issues_count": 0,
            "description_html": "",
            "updated_at": "2024-02-13T21:50:55.094Z",
            "ci_default_git_depth": 20,
            "ci_forward_deployment_enabled": True,
            "ci_forward_deployment_rollback_allowed": True,
            "ci_job_token_scope_enabled": False,
            "ci_separated_caches": True,
            "ci_allow_fork_pipelines_to_run_in_parent_project": True,
            "build_git_strategy": "fetch",
            "keep_latest_artifact": True,
            "restrict_user_defined_variables": False,
            "runners_token": "GR1348941JrYo2y6zAyBXmQ5KzZfm",
            "runner_token_expiration_interval": None,
            "group_runners_enabled": True,
            "auto_cancel_pending_pipelines": "enabled",
            "build_timeout": 3600,
            "auto_devops_enabled": True,
            "auto_devops_deploy_strategy": "continuous",
            "ci_config_path": None,
            "public_jobs": True,
            "shared_with_groups": [],
            "only_allow_merge_if_pipeline_succeeds": True,
            "allow_merge_on_skipped_pipeline": None,
            "request_access_enabled": True,
            "only_allow_merge_if_all_discussions_are_resolved": True,
            "remove_source_branch_after_merge": True,
            "printing_merge_request_link_enabled": True,
            "merge_method": "merge",
            "squash_option": "default_off",
            "enforce_auth_checks_on_uploads": True,
            "suggestion_commit_message": None,
            "merge_commit_template": None,
            "squash_commit_template": None,
            "issue_branch_template": None,
            "autoclose_referenced_issues": True,
            "requirements_enabled": False,
            "requirements_access_level": "enabled",
            "security_and_compliance_enabled": True,
            "compliance_frameworks": [],
            "permissions": {
                "project_access": {
                    "access_level": 50,
                    "notification_level": 3
                },
                "group_access": None
            }
        }
    """
    permissions: _Permissions
